### PR TITLE
Update Fusion Terraform Provider

### PR DESCRIPTION
**Pull request by LukasZahradnik**
This PR updates the TF provider and the sample configuration

### CODE REVIEW

**Comment by mikenelson-io** [comment]
fusion-pm-lab repo samples will need to be updated.

**Comment by LukasZahradnik** [comment]
@mikenelson-io I can't find the fusion-pm-lab repo

**Comment by mikenelson-io** [comment]
> @mikenelson-io I can't find the fusion-pm-lab repo

You should now have access to this repo - https://github.com/PureStorage-OpenConnect/fusion-pm-lab

**Comment by mikenelson-io** [comment]
> @mikenelson-io I can't find the fusion-pm-lab repo

@LukasZahradnik Please be advised that the fusion-pm-lab repo only contains specific sample files for the pm lab and cannot be used anywhere else.

**Comment by LukasZahradnik** [comment]
@mikenelson-io I opened a PR in the fusion-pm-lab repo.

**Review by vromash — APPROVED** [review]

**Review by andreepyro — APPROVED** [review]
LGTM

**Pull request merged**
