### PR TITLE
Introduce new workflow

### PR DESCRIPTION
**Pull request by DenDen039**
Deleted:
    `main.yml` workflow

Added:
    `create-devkit-release.yml `workflow
    `patch-devkit-release.yml` workflow

Fixed:
    `linux/amd64` container size decreased

To create new release:
    Use `patch-devkit-release`. 
    It will create release branch and release.
    It will publish latest and specific version of devkit image.

To patch release branch:
    Add new commit to this branch. 
    Trigger `patch-devkit-release` workflow to publish patch version. 
    Release with patch will be created.
    Publishing latest image is optional.
    
Releases will contain 2 tar images of devkit

### CODE REVIEW

**Comment by DenDen039** [comment]
In this approach we need to add all release/* branches as protected

**Review by mikenelson-io — COMMENTED** [review]
@DenDen039  What branch protection rules are required for this PR?
image

**Comment by DenDen039** [comment]
> @DenDen039 What branch protection rules are required for this PR? image

You can leave it as a default if you don't have any requirements

**Comment by DenDen039** [comment]
@mikenelson-io we also need to enable write permissions to workflow
image

**Review by mikenelson-io — APPROVED** [review]

**Review by pure-blim — APPROVED** [review]

**Pull request merged**
